theme: minima
title: Mathieu AMIAUD
author: Mathieu Amiaud
email: matthieu.amiaud@gmail.com
description: > # This is the website of Mathieu Amiaud

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
